services:
  db:
    image: postgres:16-alpine
    container_name: kormek-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: kormek
      POSTGRES_PASSWORD: kormek_secret
      POSTGRES_DB: kormek
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
